spring.application.name=app

# Banco de dados
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/votacao}
spring.datasource.username=${DB_USER:admin}
spring.datasource.password=${DB_PASSWORD:admin}

# JPA
spring.jpa.open-in-view=false
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.jdbc.time_zone=UTC

spring.flyway.enabled=true

server.shutdown=graceful

management.endpoints.web.exposure.include=health

votacao.sessao.duracao-padrao=1m
